services:
    _defaults:
        autowire: true
        autoconfigure: true

    arguments: $connection: '@doctrine.dbal.default_connection'
    
    Arminfrey\ContaoGbmBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}
    
