services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    
    Arminfrey\ContaoGbmBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}
        arguments:
        - '@doctrine.dbal.default_connection'

    Arminfrey\ContaoGbmBundle\Services\SendMail:
        resource ../contao
        arguments:
        - '@doctrine.dbal.default_connection'
