services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    monolog.logger.contao:
        class: Monolog\Logger
        decorates: container.logger
        decoration_priority: 100
    logger:
        alias: $monolog.logger.contao
        
    Arminfrey\ContaoGbmBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}
        arguments:
        - '@doctrine.dbal.default_connection'

    Arminfrey\ContaoGbmBundle\SendMail\SendMail:
        class: Arminfrey\ContaoGbmBundle\SendMail\SendMail
        arguments:
        - '@doctrine.dbal.default_connection'
        - request_stack
        public: true
