services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Arminfrey\ContaoGbmBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}

    arminfrey.contaogbmbundle.sendmail:
    class: Arminfrey\ContaGbmBundle\SendMail
    arguments:
        - '@doctrine.dbal.default_connection'
