services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Arminfrey\ContaoGbmBundle\:
        resource: '../src'
        exclude: '../src/{ContaoManager,DependencyInjection}'

    contaogbmbundle.contao.classes.sendmail:
    class: 'Arminfrey\ContaGbmBundle\contao\classes\SendMail'
    arguments:
        - '@doctrine.dbal.default_connection'
