services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Arminfrey\ContaoGbmBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}

    Arminfrey\ContaoGbmBundle\Contao\Classes\SendMail:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
