services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    Arminfrey\ContaoGbmBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}
        arguments:
        - '@doctrine.dbal.default_connection'

    Arminfrey\ContaoGbmBundle\SendMail\SendMail:
        class: Arminfrey\ContaoGbmBundle\SendMail\SendMail
        arguments:
        - '@doctrine.dbal.default_connection'
        public: true
